baseURL = "https://mazdakn.github.io"
languageCode = "en-us"
title = "Mazdak Nasab"
theme = "mainroad"

[Author]
  name = "Mazdak Nasab"
  bio = "This is me"
  avatar = "img/mazdak1.jpg"

[Params]
  description = "Mazdak Nasab's personal page"
  copyright = "Mazdak Nasab"

[Params.logo]
  subtitle = "A software approach to network systems"

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets.social]
  linkedin = "mazdakn"
  github = "mazdakn"
  email = "mazdak.nasab@gmail.com"

[menu]
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/"
  weight = -100

[Params.style.vars]
  highlightColor = "#1c3da6"
